Update gradle.yml

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -91,15 +91,21 @@ jobs:
       - name: Execute remote commands
         run: |
           ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
-          sudo fuser -k 8081/tcp;
-          sleep 3;
-          cd /home/ubuntu/page;
-          nohup java -jar *-SNAPSHOT.jar --spring.profiles.active=build > app.log 2>&1 &
-          sleep 5;
-          if ! sudo lsof -i :8081 -sTCP:LISTEN -t; then
-            echo 'Application failed to start!';
-            exit 1;
-          fi;"
+            sudo fuser -k 8081/tcp &&
+            cd /home/ubuntu/page &&
+            nohup java -jar *-SNAPSHOT.jar --spring.profiles.active=build > app.log 2>&1 &"
+
+        # run: |
+        #   ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
+        #   sudo fuser -k 8081/tcp;
+        #   sleep 3;
+        #   cd /home/ubuntu/page;
+        #   nohup java -jar *-SNAPSHOT.jar --spring.profiles.active=build > app.log 2>&1 &
+        #   sleep 5;
+        #   if ! sudo lsof -i :8081 -sTCP:LISTEN -t; then
+        #     echo 'Application failed to start!';
+        #     exit 1;
+        #   fi;"
 
 
   dependency-submission:
